package freecell.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCOUNT.
 */
public class Account {

    private Long id;
    private String Account;
    private String UserName;
    private String Status;
    private String Message;
    private String Url;

    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    public Account(Long id, String Account, String UserName, String Status, String Message, String Url) {
        this.id = id;
        this.Account = Account;
        this.UserName = UserName;
        this.Status = Status;
        this.Message = Message;
        this.Url = Url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return Account;
    }

    public void setAccount(String Account) {
        this.Account = Account;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getMessage() {
        return Message;
    }

    public void setMessage(String Message) {
        this.Message = Message;
    }

    public String getUrl() {
        return Url;
    }

    public void setUrl(String Url) {
        this.Url = Url;
    }

}
