package freecell.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACTS.
 */
public class Contacts {

    private Long id;
    private String contact_id;
    private String contact_name;
    private String contact_number;
    private String contact_imageUri;
    private String contact_imageLocalUri;
    private String username;
    private String contact_email;
    private Boolean isFreeCell;
    private String fifteen_digit_number;

    public Contacts() {
    }

    public Contacts(Long id) {
        this.id = id;
    }

    public Contacts(Long id, String contact_id, String contact_name, String contact_number, String contact_imageUri, String contact_imageLocalUri, String username, String contact_email, Boolean isFreeCell, String fifteen_digit_number) {
        this.id = id;
        this.contact_id = contact_id;
        this.contact_name = contact_name;
        this.contact_number = contact_number;
        this.contact_imageUri = contact_imageUri;
        this.contact_imageLocalUri = contact_imageLocalUri;
        this.username = username;
        this.contact_email = contact_email;
        this.isFreeCell = isFreeCell;
        this.fifteen_digit_number = fifteen_digit_number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContact_id() {
        return contact_id;
    }

    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    public String getContact_name() {
        return contact_name;
    }

    public void setContact_name(String contact_name) {
        this.contact_name = contact_name;
    }

    public String getContact_number() {
        return contact_number;
    }

    public void setContact_number(String contact_number) {
        this.contact_number = contact_number;
    }

    public String getContact_imageUri() {
        return contact_imageUri;
    }

    public void setContact_imageUri(String contact_imageUri) {
        this.contact_imageUri = contact_imageUri;
    }

    public String getContact_imageLocalUri() {
        return contact_imageLocalUri;
    }

    public void setContact_imageLocalUri(String contact_imageLocalUri) {
        this.contact_imageLocalUri = contact_imageLocalUri;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getContact_email() {
        return contact_email;
    }

    public void setContact_email(String contact_email) {
        this.contact_email = contact_email;
    }

    public Boolean getIsFreeCell() {
        return isFreeCell;
    }

    public void setIsFreeCell(Boolean isFreeCell) {
        this.isFreeCell = isFreeCell;
    }

    public String getFifteen_digit_number() {
        return fifteen_digit_number;
    }

    public void setFifteen_digit_number(String fifteen_digit_number) {
        this.fifteen_digit_number = fifteen_digit_number;
    }

}
