package freecell.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROOMS.
 */
public class Rooms {

    private Long id;
    private String account;
    private String room;
    private String nickname;
    private String password;
    private Integer need_join;
    private String group_image;

    public Rooms() {
    }

    public Rooms(Long id) {
        this.id = id;
    }

    public Rooms(Long id, String account, String room, String nickname, String password, Integer need_join, String group_image) {
        this.id = id;
        this.account = account;
        this.room = room;
        this.nickname = nickname;
        this.password = password;
        this.need_join = need_join;
        this.group_image = group_image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getNeed_join() {
        return need_join;
    }

    public void setNeed_join(Integer need_join) {
        this.need_join = need_join;
    }

    public String getGroup_image() {
        return group_image;
    }

    public void setGroup_image(String group_image) {
        this.group_image = group_image;
    }

}
