package freecell.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_TRACKING.
 */
public class UserTracking {

    private Long id;
    private String tracking_id;
    private String user_id;
    private String session_id;
    private String time_start;
    private String last_active_time;
    private String close_time;
    private String sent;
    private String ack;
    private String device_id;

    public UserTracking() {
    }

    public UserTracking(Long id) {
        this.id = id;
    }

    public UserTracking(Long id, String tracking_id, String user_id, String session_id, String time_start, String last_active_time, String close_time, String sent, String ack, String device_id) {
        this.id = id;
        this.tracking_id = tracking_id;
        this.user_id = user_id;
        this.session_id = session_id;
        this.time_start = time_start;
        this.last_active_time = last_active_time;
        this.close_time = close_time;
        this.sent = sent;
        this.ack = ack;
        this.device_id = device_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTracking_id() {
        return tracking_id;
    }

    public void setTracking_id(String tracking_id) {
        this.tracking_id = tracking_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getSession_id() {
        return session_id;
    }

    public void setSession_id(String session_id) {
        this.session_id = session_id;
    }

    public String getTime_start() {
        return time_start;
    }

    public void setTime_start(String time_start) {
        this.time_start = time_start;
    }

    public String getLast_active_time() {
        return last_active_time;
    }

    public void setLast_active_time(String last_active_time) {
        this.last_active_time = last_active_time;
    }

    public String getClose_time() {
        return close_time;
    }

    public void setClose_time(String close_time) {
        this.close_time = close_time;
    }

    public String getSent() {
        return sent;
    }

    public void setSent(String sent) {
        this.sent = sent;
    }

    public String getAck() {
        return ack;
    }

    public void setAck(String ack) {
        this.ack = ack;
    }

    public String getDevice_id() {
        return device_id;
    }

    public void setDevice_id(String device_id) {
        this.device_id = device_id;
    }

}
